services:
  airline-system-database:
    build: 
      context: ./SQL-Server-Database/SQL
      dockerfile: Dockerfile.dev
    container_name: airline-system-database
    ports:
      - "5555:1433"
    environment:
      SA_PASSWORD: "Root123!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    command: /bin/bash /docker-entrypoint-initdb.d/initdatabases.sh && wait  
  airline-system-api:
    build: 
      context: ./AirlineManagementSystemSpring
      dockerfile: Dockerfile.dev
    container_name: airline-system-api
    ports:
      - "8080:8080"
    depends_on:
      - airline-system-database
    environment:
      WAIT_HOSTS: airline-system-database:1433
    restart: on-failure
  airline-system-interface:
    build: 
      context: ./Interface-AirManagementSystem-Angular
      dockerfile: Dockerfile.dev
    container_name: airline-system-interface
    ports:
      - "9999:80"
    depends_on:
      - airline-system-api
    restart: on-failure    
volumes:
  sqlserver_data: